security:
    encoders:
        App\Core\Model\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Core\Model\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            lazy: true
            stateless: true
            guard:
                authenticators:
                    - App\Core\Security\JwtAuthenticator

    access_control:
        - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/validation, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]