auth_controllers:
    resource: ../../src/Authentication/Controller/
    type: annotation

user_controllers:
    resource: ../../src/User/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
