<?php

namespace App\Authentication;

class Message
{
    // ERROR MESSAGES
    public const AUTH_REGISTER_USER_EXISTS = "AUTH_REGISTER_USER_EXISTS";
    public const AUTH_REGISTER_RESEND_CONFIRM_EMAIL = "AUTH_REGISTER_RESEND_CONFIRM_EMAIL";
    public const AUTH_LOGIN_WRONG_CREDENTIALS = "AUTH_LOGIN_WRONG_CREDENTIALS";
    public const AUTH_REFRESH_TOKEN_NOT_FOUND = "AUTH_REFRESH_TOKEN_NOT_FOUND";
    public const AUTH_REFRESH_TOKEN_EXPIRED = "AUTH_REFRESH_TOKEN_EXPIRED";
    public const AUTH_VALIDATION_FAILED = "AUTH_VALIDATION_FAILED";

    // SUCCESS MESSAGES
    public const AUTH_VALIDATION_SUCCESS =  "AUTH_VALIDATION_SUCCESS";
    public const AUTH_REGISTER_SUCCESS =  "AUTH_REGISTER_SUCCESS";

}