<?php

namespace App\Core;

class Message
{
    // ERROR MESSAGES
    public const SECURITY_AUTH_REQUIRED = "SECURITY_AUTH_REQUIRED";
    public const SECURITY_AUTH_TOKEN_EXPIRED = "SECURITY_AUTH_TOKEN_EXPIRED";
    public const SECURITY_AUTH_WAITING_VALIDATION = "SECURITY_AUTH_WAITING_VALIDATION";
}
